name: Test Go

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'svb/**'

jobs:
  test:
    name: Go tests
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-latest]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - uses: actions/checkout@v2
      - name: Test All
        working-directory: ./svb
        run: |
          go test -timeout 30 m ./...
        env:
          MATRIX_OS: ${{ matrix.os }}
